<script>
    require([
        "prototype"
    ], function () {
        window.specm_ajax_choosecourier = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/choosecourier')?>';
        window.specm_ajax_confirmbooking = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/confirmbooking')?>';
        window.specm_ajax_preprintlabel = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/preprintlabel')?>';
        window.specm_ajax_loginregister = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/loginregister')?>';
        window.specm_ajax_addresscorrector = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/addresscorrector')?>';
        window.specm_ajax_settings = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/settings')?>';
        window.specm_ajax_trackinghistory = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/trackinghistory')?>';
        window.specm_ajax_getstatus = '<?= /** @noEscape */ $block->getUrl('shippop/ajax/getstatus')?>';
        window.specm_translate_sub_choose_parcel = '<?= __("Orders will appeared if order status is processing or order payment method is COD") ?>';
    });
</script>