<?php
$email = $block->getEmail();
$server = $block->getServer();
$member = $block->getMember();
$logout = $block->logoutUrl();
$pickup = $block->getPickup();

$country = ($server == "TH") ? __("Thailand") : __("Malaysia");

$pickup_name = $pickup_tel = $pickup_address = "";
$pickup_province = $pickup_district = $pickup_state = $pickup_postcode = "";
if (!empty($pickup)) {
    $pickup_name = (!empty($pickup["address_name"])) ? $pickup["address_name"] : "";
    $pickup_tel = (!empty($pickup["address_tel"])) ? $pickup["address_tel"] : "";
    $pickup_address = (!empty($pickup["address"])) ? $pickup["address"] : "";

    $pickup_state = (!empty($pickup["state"])) ? $pickup["state"] : "";
    $pickup_district = (!empty($pickup["district"])) ? $pickup["district"] : "";
    $pickup_province = (!empty($pickup["province"])) ? $pickup["province"] : "";
    $pickup_postcode = (!empty($pickup["postcode"])) ? $pickup["postcode"] : "";
}

$billing_name = $billing_name_title = $billing_tax_id = $billing_tel = $billing_address = "";
if (!empty($member) && $member["status"]) {
    $billing_name = (!empty($member["data"]["billing"]["name"])) ? $member["data"]["billing"]["name"] : "";
    $billing_name_title = (!empty($member["data"]["billing"]["name_title"])) ? $member["data"]["billing"]["name_title"] : "";
    $billing_tax_id = (!empty($member["data"]["billing"]["tax_id"])) ? $member["data"]["billing"]["tax_id"] : "";
    $billing_tel = (!empty($member["data"]["billing"]["phone"])) ? $member["data"]["billing"]["phone"] : "";
    $billing_address = (!empty($member["data"]["billing"]["address"])) ? $member["data"]["billing"]["address"] : "";
}
?>

<div class="wrap">
    <a href="<?= $block->escapeUrl($logout) ?>">
        <button style="color: red;border: solid 1px red;position: absolute;right: 20px;background: white;" 
            type="button" class="button button-danger specm-logout-btn">
            <?= $block->escapeHtml(__('Logout')); ?>
        </button>
    </a>
    <form method="post" name="settings" action="#">
        <h2 style="margin-top: 10px;"><?= $block->escapeHtml(__('Settings')); ?></h2>
        <hr>
        <table class="form-table" role="presentation">
            <tbody>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('Email')); ?></th>
                    <td>
                        <input type="email" class="specm-settings-input" 
                            value="<?= $block->escapeHtmlAttr($email) ?>" 
                            readonly="" style="opacity: 0.5;">
                        </td>
                </tr>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('Choose country')); ?></th>
                    <td>
                        <input type="text" class="specm-settings-input" 
                        value="<?= $block->escapeHtmlAttr($country) ?>" 
                        readonly="" style="opacity: 0.5;">
                    </td>
                </tr>
            </tbody>
        </table>
        <h2 style="margin-top: 10px;">
            <?= $block->escapeHtml(__("Store's address for pick-up service")); ?>
        </h2>
        <hr>
        <table class="form-table" role="presentation">
            <tbody>
                <tr>
                    <th scope="row">
                        <?= $block->escapeHtml(__("Name and Surname")); ?><span class="red-star-setting">*</span>
                    </th>
                    <td>
                        <input type="text" class="specm-settings-input" 
                            id="address_name" name="specm_settings[address][name]" 
                            value="<?= $block->escapeHtmlAttr($pickup_name) ?>" required>
                        </td>
                </tr>
                <tr>
                    <th scope="row">
                        <?= $block->escapeHtml(__("Contact number")); ?><span class="red-star-setting">*</span>
                    </th>
                    <td>
                        <input type="text" class="specm-settings-input" id="address_tel" 
                        name="specm_settings[address][tel]" pattern="[0-9]{10}" 
                        value="<?= $block->escapeHtmlAttr($pickup_tel) ?>" required>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <?= $block->escapeHtml(__("Address")); ?><span class="red-star-setting">*</span>
                    </th>
                    <td>
                        <textarea class="specm-settings-input" name="specm_settings[address][address]" id="address_address" cols="20" rows="5" 
                        placeholder="<?= $block->escapeHtml(__("Please fill in your address")); ?>" required><?= $block->escapeHtmlAttr($pickup_address) ?></textarea>
                    </td>
                </tr>
                <?php if ($server == "MY"): ?>
                    <tr>
                        <th scope="row">
                            <?= $block->escapeHtml(__("State")); ?>
                            <span class="red-star-setting">*</span>
                        </th>
                        <td>
                            <input type="text" class="specm-settings-input" id="address_state" 
                            name="specm_settings[address][state]" 
                            value="<?= $block->escapeHtmlAttr($pickup_state) ?>" required>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            <?= $block->escapeHtml(__("District")); ?>
                            <span class="red-star-setting">*</span>
                        </th>
                        <td>
                            <input type="text" class="specm-settings-input" id="address_district" 
                            name="specm_settings[address][district]" 
                            value="<?= $block->escapeHtmlAttr($pickup_district) ?>" required>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            <?= $block->escapeHtml(__("Province")); ?>
                            <span class="red-star-setting">*</span>
                        </th>
                        <td>
                            <input type="text" class="specm-settings-input" id="address_province" 
                            name="specm_settings[address][province]" 
                            value="<?= $block->escapeHtmlAttr($pickup_province) ?>" required>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">
                            <?= $block->escapeHtml(__("Postcode")); ?>
                            <span class="red-star-setting">*</span>
                        </th>
                        <td>
                            <input type="number" class="specm-settings-input" id="address_postcode" 
                            name="specm_settings[address][postcode]" min="1" step="1" 
                            value="<?= $block->escapeHtmlAttr($pickup_postcode) ?>" required>
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
        <h2 style="margin-top: 10px;"><?= $block->escapeHtml(__("Billing and invoice addresses")); ?></h2>
        <hr>
        <table class="form-table" role="presentation">
            <tbody>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__("Name and Surname")); ?></th>
                    <td>
                        <input type="hidden" class="specm-settings-input" 
                        id="billing_name_title" name="specm_settings[billing][name_title]" 
                        value="<?= $block->escapeHtmlAttr($billing_name_title) ?>">

                        <input type="text" class="specm-settings-input" 
                        id="billing_name" name="specm_settings[billing][name]" 
                        value="<?= $block->escapeHtmlAttr($billing_name) ?>">
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__("Tax ID")); ?></th>
                    <td>
                        <input type="text" class="specm-settings-input" 
                        id="billing_tax_id" name="specm_settings[billing][tax_id]" 
                        value="<?= $block->escapeHtmlAttr($billing_tax_id) ?>">
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__("Contact number")); ?></th>
                    <td>
                        <input type="text" class="specm-settings-input" 
                        id="billing_tel" name="specm_settings[billing][tel]" 
                        pattern="[0-9]{10}" value="<?= $block->escapeHtmlAttr($billing_tel) ?>">
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__("Address")); ?></th>
                    <td>
                        <textarea name="specm_settings[billing][address]" class="specm-settings-input" id="billing_address" cols="20" style="resize: none;" 
                        rows="5" placeholder="<?= $block->escapeHtml(__("Please fill in your address")); ?>"><?= $block->escapeHtmlAttr($billing_address) ?></textarea>
                    </td>
                </tr>
            </tbody>
        </table> 
        <button type="submit" class="button button-primary primary">
            <?= $block->escapeHtml(__("Update")); ?>
        </button>
    </form>
</div>

<div id="shippop-popup-modal" style="display: none;">
    <script id="address-corrector-template" type="text/x-magento-template">
        <div style="padding: 15px;height: 500px;overflow-y: auto;">
            <div id="address-corrector-form" style="padding: 15px;text-align: left;">
                <h2><?= $block->escapeHtml(__('Pick up address')) ?></h2>
                <% _.each(address_address_suggestion, function(data_object, value) { %>
                    <% if (value == 0) { %>
                            <p> <input checked type="radio" name="correct_address" value="<%= value %>" 
                                    data-full="<%= data_object.full %>" data-state="<%= data_object.state %>" 
                                    data-district="<%= data_object.district %>" data-province="<%= data_object.province %>" 
                                    data-postcode="<%= data_object.postcode %>" /> <%= data_object.full %> </p>
                        <% } else { %>
                            <p> <input type="radio" name="correct_address" value="<%= value %>" 
                                    data-full="<%= data_object.full %>" data-state="<%= data_object.state %>" 
                                    data-district="<%= data_object.district %>" data-province="<%= data_object.province %>" 
                                    data-postcode="<%= data_object.postcode %>" /> <%= data_object.full %> </p>
                        <% } %>
                <% }) %>

                <hr style="margin-top: 20px;margin-bottom: 20px;" />

                <h2><?= $block->escapeHtml(__('Billing address')) ?></h2>
                <% _.each(billing_address_suggestion, function(data_object, value) { %>
                    <% if (value == 0) { %>
                            <p> <input checked type="radio" name="correct_address_billing" value="<%= value %>" 
                                    data-full="<%= data_object.full %>" data-state="<%= data_object.state %>" 
                                    data-district="<%= data_object.district %>" data-province="<%= data_object.province %>" 
                                    data-postcode="<%= data_object.postcode %>" /> <%= data_object.full %> </p>
                        <% } else { %>
                            <p> <input type="radio" name="correct_address_billing" value="<%= value %>" 
                                    data-full="<%= data_object.full %>" data-state="<%= data_object.state %>" 
                                    data-district="<%= data_object.district %>" data-province="<%= data_object.province %>" 
                                    data-postcode="<%= data_object.postcode %>" /> <%= data_object.full %> </p>
                        <% } %>
                <% }) %>

            </div>
            <div class="clearfix"></div>
        </div>
    </script>
</div>